[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_vault = "2DFk2oyDSY6dh8cCmnQQ7iayybUuotLwLetoCHqE5dot"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_gill = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/gill/**/*.ts"
